ALTER TABLE files ADD COLUMN data_offset INTEGER NOT NULL DEFAULT 0;
ALTER TABLE files ADD COLUMN naxis1 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE files ADD COLUMN naxis2 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE files ADD COLUMN bitpix INTEGER NOT NULL DEFAULT 0;
ALTER TABLE files ADD COLUMN bzero INTEGER NOT NULL DEFAULT 0;
